/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Enhanced with theme-aware materials
*/

import React, { useRef, useMemo, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useGSAP } from "@gsap/react";
import gsap from "gsap";
import { useTheme } from "../context/ThemeContext";
import * as THREE from "three";

export function Planet(props) {
  const shapeContainer = useRef(null);
  const shperesContainer = useRef(null);
  const ringContainer = useRef(null);
  const sphereMeshRef = useRef(null);
  const sphere2MeshRef = useRef(null);
  const ringMeshRef = useRef(null);
  const { nodes, materials } = useGLTF("/models/Planet.glb");
  const { theme } = useTheme();

  // Create inverted material for light mode - use MeshBasicMaterial (unaffected by lights)
  // Using slate gray for visibility against white but contrast with black text
  const invertedMaterial = useMemo(() => {
    return new THREE.MeshBasicMaterial({
      color: "#94a3b8", // Slate 400 - visible but not pitch black
      transparent: false,
    });
  }, []);

  // Create inverted ring material - bright blue for visibility
  const invertedRingMaterial = useMemo(() => {
    return new THREE.MeshBasicMaterial({
      color: "#2563eb", // Blue 600 - matches theme accent
      transparent: false,
    });
  }, []);

  // Glass Theme Materials - Cyan/Dark Blue aesthetic
  const glassMaterial = useMemo(() => {
    return new THREE.MeshBasicMaterial({
      color: "#1a1a2e", // Dark Blue/Purple base
      transparent: false,
    });
  }, []);

  const glassRingMaterial = useMemo(() => {
    return new THREE.MeshBasicMaterial({
      color: "#00d4ff", // Cyan accent
      transparent: true,
      opacity: 0.8,
    });
  }, []);

  // Force material update when theme changes
  useEffect(() => {
    let targetSphereMat = materials["Material.002"];
    let targetRingMat = materials["Material.001"];

    if (theme === 'light') {
      targetSphereMat = invertedMaterial;
      targetRingMat = invertedRingMaterial;
    } else if (theme === 'glass') {
      targetSphereMat = glassMaterial;
      targetRingMat = glassRingMaterial;
    }

    if (sphereMeshRef.current) {
      sphereMeshRef.current.material = targetSphereMat;
      sphereMeshRef.current.material.needsUpdate = true;
    }
    if (sphere2MeshRef.current) {
      sphere2MeshRef.current.material = targetRingMat;
      sphere2MeshRef.current.material.needsUpdate = true;
    }
    if (ringMeshRef.current) {
      ringMeshRef.current.material = targetRingMat;
      ringMeshRef.current.material.needsUpdate = true;
    }
  }, [theme, invertedMaterial, invertedRingMaterial, glassMaterial, glassRingMaterial, materials]);

  useGSAP(() => {
    const tl = gsap.timeline();
    tl.from(shapeContainer.current.position, {
      y: 5,
      duration: 3,
      ease: "circ.out",
    });
    tl.from(
      shperesContainer.current.rotation,
      {
        x: 0,
        y: Math.PI,
        z: -Math.PI,
        duration: 10,
        ease: "power1.inOut",
      },
      "-=25%"
    );
    tl.from(
      ringContainer.current.rotation,
      {
        x: 0.8,
        y: 0,
        z: 0,
        duration: 10,
        ease: "power1.inOut",
      },
      "<"
    );
  }, []);

  const getMaterial = (type) => {
    if (theme === 'light') {
      return type === 'sphere' ? invertedMaterial : invertedRingMaterial;
    }
    if (theme === 'glass') {
      return type === 'sphere' ? glassMaterial : glassRingMaterial;
    }
    return type === 'sphere' ? materials["Material.002"] : materials["Material.001"];
  };

  return (
    <group ref={shapeContainer} {...props} dispose={null}>
      <group ref={shperesContainer}>
        <mesh
          ref={sphereMeshRef}
          castShadow={theme === 'dark'}
          receiveShadow={theme === 'dark'}
          geometry={nodes.Sphere.geometry}
          material={getMaterial('sphere')}
          rotation={[0, 0, 0.741]}
        />
        <mesh
          ref={sphere2MeshRef}
          castShadow={theme === 'dark'}
          receiveShadow={theme === 'dark'}
          geometry={nodes.Sphere2.geometry}
          material={getMaterial('ring')}
          position={[0.647, 1.03, -0.724]}
          rotation={[0, 0, 0.741]}
          scale={0.223}
        />
      </group>
      <mesh
        ref={(el) => {
          ringMeshRef.current = el;
          ringContainer.current = el;
        }}
        castShadow={theme === 'dark'}
        receiveShadow={theme === 'dark'}
        geometry={nodes.Ring.geometry}
        material={getMaterial('ring')}
        rotation={[-0.124, 0.123, -0.778]}
        scale={2}
      />
    </group>
  );
}

useGLTF.preload("/models/Planet.glb");
